/**
 * Comprehensive list of Indian Railway Stations
 * Format: "Station Name (CODE)"
 * Sorted alphabetically for easy lookup
 */
export const INDIAN_RAILWAY_STATIONS: string[] = [
  "Agra Cantt (AGC)",
  "Agra Fort (AF)",
  "Ahmedabad (ADI)",
  "Ajmer (AII)",
  "Akola (AK)",
  "Aligarh (ALJN)",
  "Allahabad (ALD)",
  "Alwar (AWR)",
  "Ambala (UMB)",
  "Ambala Cantt (AMBK)",
  "Amritsar (ASR)",
  "Amravati (AWB)",
  "Anand (ANND)",
  "Anantapur (ATP)",
  "Asansol (ASN)",
  "Aurangabad (AWB)",
  "Ayodhya (AY)",
  "Azamgarh (AZM)",
  "Badlapur (BUD)",
  "Balasore (BLS)",
  "Bangalore City (SBC)",
  "Bangalore Cantt (BNC)",
  "Barddhaman (BWN)",
  "Bareilly (BE)",
  "Baroda (BRC)",
  "Bhatinda (BTI)",
  "Bhavnagar (BVC)",
  "Bhopal (BPL)",
  "Bhubaneswar (BBS)",
  "Bhuj (BHUJ)",
  "Bikaner (BKN)",
  "Bilaspur (BSP)",
  "Borivali (BVI)",
  "Brahmapur (BAM)",
  "Burhanpur (BPQ)",
  "Burdwan (BWN)",
  "Calicut / Kozhikode (CLT)",
  "Chennai Central (MAS)",
  "Chennai Egmore (MS)",
  "Chandigarh (CDG)",
  "Chhindwara (CI)",
  "Chittorgarh (COR)",
  "Coimbatore (CBE)",
  "Cuttack (CTC)",
  "Dahanu Road (DRD)",
  "Darbhanga (DBG)",
  "Daund (DD)",
  "Dehradun (DDN)",
  "Dhanbad (DHN)",
  "Dholpur (DHO)",
  "Dibrugarh (DBRG)",
  "Dindigul (DG)",
  "Durg (DURG)",
  "Ernakulam (ERS)",
  "Erode (ED)",
  "Faizabad (FD)",
  "Faridabad (FDB)",
  "Firozpur (FZR)",
  "Gandhidham (GIMB)",
  "Gaya (GAYA)",
  "Gorakhpur (GKP)",
  "Gulbarga / Kalaburagi (GR)",
  "Guntur (GNT)",
  "Gurgaon / Gurugram (GGN)",
  "Guwahati (GHY)",
  "Gwalior (GWL)",
  "Hazrat Nizamuddin (NZM)",
  "Howrah (HWH)",
  "Hubli (UBL)",
  "Hyderabad (HYB)",
  "Hyderabad Deccan (HYD)",
  "Indore (INDB)",
  "Itarsi (ET)",
  "Jabalpur (JBP)",
  "Jaipur (JP)",
  "Jalandhar (JUC)",
  "Jalgaon (JL)",
  "Jammu Tawi (JAT)",
  "Jamnagar (JAM)",
  "Jhansi (JHS)",
  "Jodhpur (JU)",
  "Jorhat (JTN)",
  "Junagarh Road (JND)",
  "Kacheguda (KCG)",
  "Kakinada (CCT)",
  "Kalyan (KYN)",
  "Kankavali (KKRI)",
  "Kanpur Central (CNB)",
  "Karnal (KUN)",
  "Katpadi (KPD)",
  "Katihar (KIR)",
  "Khammam (KMT)",
  "Kochi (ERS)",
  "Kolhapur (KOP)",
  "Kolkata (KOAA)",
  "Kollam (QLN)",
  "Kota (KOTA)",
  "Kottayam (KTYM)",
  "Lucknow (LKO)",
  "Lucknow NR (LKO)",
  "Ludhiana (LDH)",
  "Madgaon / Goa (MAO)",
  "Madurai (MDU)",
  "Manmad (MMR)",
  "Margao (MAO)",
  "Mathura (MTJ)",
  "Meerut City (MTC)",
  "Mirzapur (MZP)",
  "Moradabad (MB)",
  "Mumbai Central (MMCT)",
  "Mumbai Chhatrapati Shivaji Maharaj Terminus (CSMT)",
  "Mumbai Dadar (DR)",
  "Mumbai Lokmanya Tilak Terminus (LTT)",
  "Munger (MFP)",
  "Muzaffarpur (MFP)",
  "Mysuru (MYS)",
  "Nagpur (NGP)",
  "Nanded (NED)",
  "Nashik Road (NK)",
  "New Delhi (NDLS)",
  "New Jalpaiguri (NJP)",
  "Panvel (PNVL)",
  "Pathankot (PTK)",
  "Patna (PNBE)",
  "Patna Sahib (PNRS)",
  "Patiala (PTA)",
  "Pune (PUNE)",
  "Puri (PURI)",
  "Raipur (R)",
  "Rajkot (RJT)",
  "Rajahmundry (RJY)",
  "Ramgundam (RGPD)",
  "Ranchi (RNC)",
  "Rohtak (ROK)",
  "Roorkee (RK)",
  "Rourkela (ROU)",
  "Sabarmati (SBI)",
  "Salem (SA)",
  "Samastipur (SPJ)",
  "Satna (STA)",
  "Secunderabad (SC)",
  "Sealdah (SDAH)",
  "Shivaji Nagar (SHV)",
  "Shimla (SML)",
  "Shoranur (SRR)",
  "Siliguri (SGUJ)",
  "Sirsa (SSA)",
  "Solapur (SUR)",
  "Sonepat (SNP)",
  "Srinagar (SRE)",
  "Surat (ST)",
  "Tata Nagar / Jamshedpur (TATA)",
  "Thiruvanthapuram / Trivandrum (TVC)",
  "Tirunelveli (TEN)",
  "Tirupati (TPTY)",
  "Tirupur (TUP)",
  "Trichy / Tiruchirappalli (TPJ)",
  "Tumkur (TK)",
  "Udaipur City (UDZ)",
  "Ujjain (UJN)",
  "Vadodara (BRC)",
  "Varanasi (BSB)",
  "Vasco Da Gama (VSG)",
  "Vijayawada (BZA)",
  "Visakhapatnam (VSKP)",
  "Vizianagaram (VZM)",
  "Warangal (WL)",
  "Yasvantpur (YPR)",
  "Yesvantpur (YPR)",
].sort()
