package com.example.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.local.entity.CustomerEntity
import com.example.data.local.entity.EmployeeEntity
import com.example.data.local.entity.PurchaseEntryEntity
import com.example.data.local.entity.SupplierEntity
import com.example.data.local.entity.VisitEntity
import java.io.File

object ShareUtil {

    fun sharePdfFile(context: Context, file: File, title: String, targetPackage: String? = null) {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, title)
                putExtra(Intent.EXTRA_TEXT, "$title\nGenerated by Himat Textile Sourcing Agency")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                if (targetPackage != null) {
                    setPackage(targetPackage)
                }
            }

            if (targetPackage != null) {
                try {
                    context.startActivity(shareIntent)
                    return
                } catch (e: Exception) {
                    // WhatsApp not installed or package mismatch, fallback to chooser
                }
            }

            val chooser = Intent.createChooser(shareIntent, "Share Document via")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            Toast.makeText(context, "Could not share PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun shareWhatsAppText(context: Context, text: String, phone: String? = null) {
        try {
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
                setPackage("com.whatsapp")
            }
            context.startActivity(intent)
        } catch (e: Exception) {
            // Fallback to general share
            val fallback = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
            }
            context.startActivity(Intent.createChooser(fallback, "Share via"))
        }
    }

    fun buildCustomerReportText(
        visit: VisitEntity,
        customer: CustomerEntity?,
        entries: List<PurchaseEntryEntity>
    ): String {
        val totalAmount = entries.sumOf { it.totalAmount }
        val totalGst = entries.sumOf { it.gstAmount }
        val grandTotal = totalAmount + totalGst
        val totalCases = entries.sumOf { it.caseCount }
        val totalLoose = entries.sumOf { it.loosePieces }

        return buildString {
            appendLine("📋 *HIMAT TEXTILE — CUSTOMER DAY REPORT*")
            appendLine("─────────────────────────")
            appendLine("👤 *Customer:* ${customer?.name ?: visit.customerName}")
            appendLine("📍 *Market:* ${customer?.city ?: "—"}")
            appendLine("📅 *Date:* ${visit.date} | *Visit Code:* ${visit.visitCode}")
            appendLine("🤵 *Salesman:* ${visit.employeeName}")
            appendLine("─────────────────────────")
            appendLine("📦 *ITEMS PURCHASED:*")

            entries.groupBy { it.supplierName }.forEach { (supplier, items) ->
                appendLine("\n🏢 *${supplier}*")
                items.forEach { item ->
                    appendLine(" • *${item.itemCode}* | ${item.pieces} Pcs @ ₹${item.rate.toInt()} = ₹${item.totalAmount.toInt()}")
                    val pack = if (item.loosePieces > 0) "${item.caseCount}c + ${item.loosePieces}L" else "${item.caseCount}c"
                    appendLine("   Packing: $pack")
                    if (!item.mixedPackNote.isNullOrBlank()) {
                        appendLine("   ↳ _${item.mixedPackNote}_")
                    }
                }
            }

            appendLine("\n─────────────────────────")
            appendLine("📊 *TOTALS:*")
            appendLine("Total Quantity: ${entries.sumOf { it.pieces }} Pcs ($totalCases Cases, $totalLoose Loose)")
            appendLine("Subtotal: ₹${String.format("%,.2f", totalAmount)}")
            appendLine("Garment GST (5%): ₹${String.format("%,.2f", totalGst)}")
            appendLine("💰 *GRAND TOTAL: ₹${String.format("%,.2f", grandTotal)}*")
            appendLine("─────────────────────────")
            appendLine("_Himat Textile Garment Sourcing Agency_")
        }
    }

    fun buildSupplierCopyText(
        visit: VisitEntity,
        supplier: SupplierEntity,
        customer: CustomerEntity?,
        entries: List<PurchaseEntryEntity>
    ): String {
        val totalAmount = entries.sumOf { it.totalAmount }
        val totalGst = entries.sumOf { it.gstAmount }
        val grandTotal = totalAmount + totalGst

        return buildString {
            appendLine("🏷️ *HIMAT TEXTILE — SUPPLIER PURCHASE COPY*")
            appendLine("─────────────────────────")
            appendLine("🏭 *Supplier:* ${supplier.name} (${supplier.type})")
            appendLine("📍 *Market Area:* ${supplier.marketArea}")
            appendLine("👤 *Customer:* ${customer?.name ?: visit.customerName}")
            appendLine("📅 *Date:* ${visit.date} | *Agent:* ${visit.employeeName}")
            appendLine("─────────────────────────")
            appendLine("📋 *PURCHASE DETAILS:*")

            entries.forEach { item ->
                appendLine(" • *Order ${item.orderNo}*: ${item.itemCode}")
                appendLine("   Qty: ${item.pieces} Pcs @ ₹${item.rate.toInt()} = ₹${item.totalAmount.toInt()}")
                val packing = if (item.loosePieces > 0) "${item.caseCount} Cases + ${item.loosePieces} Loose" else "${item.caseCount} Cases"
                appendLine("   Packing: $packing (Case size: ${item.caseSize})")
                if (!item.mixedPackNote.isNullOrBlank()) {
                    appendLine("   ⚠️ *Packing Note:* _${item.mixedPackNote}_")
                }
            }

            appendLine("\n─────────────────────────")
            appendLine("Total Pcs: ${entries.sumOf { it.pieces }} Pcs")
            appendLine("Taxable Amount: ₹${String.format("%,.2f", totalAmount)}")
            appendLine("GST (5%): ₹${String.format("%,.2f", totalGst)}")
            appendLine("💰 *NET TOTAL: ₹${String.format("%,.2f", grandTotal)}*")
            appendLine("─────────────────────────")
            appendLine("_Himat Textile Sourcing Agency — Direct Booking_")
        }
    }
}
