package com.example.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.local.entity.CustomerEntity
import com.example.data.local.entity.EmployeeEntity
import com.example.data.local.entity.PurchaseEntryEntity
import com.example.data.local.entity.SupplierEntity
import com.example.data.local.entity.VisitEntity
import java.io.File

object ShareUtil {

    fun sharePdfFile(context: Context, file: File, title: String, targetPackage: String? = null) {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, title)
                putExtra(Intent.EXTRA_TEXT, "$title\nGenerated by Himat Textile Sourcing Agency")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                if (targetPackage != null) {
                    setPackage(targetPackage)
                }
            }

            if (targetPackage != null) {
                try {
                    context.startActivity(shareIntent)
                    return
                } catch (e: Exception) {
                    // WhatsApp not installed or package mismatch, fallback to chooser
                }
            }

            val chooser = Intent.createChooser(shareIntent, "Share Document via")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            Toast.makeText(context, "Could not share PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun shareWhatsAppText(context: Context, text: String, phone: String? = null) {
        try {
            if (!phone.isNullOrBlank()) {
                val clean = phone.replace("+", "").replace("-", "").replace(" ", "").trim()
                val targetPhone = if (clean.length == 10) "91$clean" else clean
                val uri = Uri.parse("https://api.whatsapp.com/send?phone=$targetPhone&text=${Uri.encode(text)}")
                val intent = Intent(Intent.ACTION_VIEW, uri).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(intent)
                return
            }

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
                setPackage("com.whatsapp")
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(intent)
        } catch (e: Exception) {
            // Fallback to general share
            val fallback = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(Intent.createChooser(fallback, "Share via").apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            })
        }
    }

    fun shareCustomerRegistrationLink(context: Context, phone: String? = null) {
        val regUrl = "https://himatsms.web.app/#/register-customer"
        val msg = """
            *श्री हिम्मत ट्रेडिंग कंपनी — नया ग्राहक खाता पंजीकरण*
            
            नमस्ते! हमारे साथ नया व्यापारिक खाता खोलने के लिए कृपया नीचे दिए गए लिंक पर जाकर अपनी बुनियादी व्यावसायिक जानकारी और आवश्यक विवरण भरें:
            
            🔗 $regUrl
            
            _नोट: फॉर्म भरने के बाद आपके नंबर पर एसएमएस ओटीपी सत्यापन होगा।_
            
            धन्यवाद!
            श्री हिम्मत ट्रेडिंग कंपनी, अहमदाबाद
        """.trimIndent()
        shareWhatsAppText(context, msg, phone)
    }

    fun shareSupplierRegistrationLink(context: Context, phone: String? = null) {
        val regUrl = "https://himatsms.web.app/#supplier-register"
        val msg = """
            *हिम्मत टेक्सटाइल — नया सप्लायर / फैब्रिक मिल पंजीकरण*
            
            नमस्कार! हिम्मत टेक्सटाइल (Himat Textile) के साथ फैब्रिक मिल / सप्लायर के रूप में जुड़ने के लिए कृपया नीचे दिए गए लिंक पर अपनी मिल व व्यावसायिक जानकारी भरें:
            
            🔗 $regUrl
            
            _नोट: फॉर्म भरने के बाद आपके नंबर पर सत्यापन होगा।_
            
            धन्यवाद!
            हिम्मत टेक्सटाइल, अहमदाबाद
        """.trimIndent()
        shareWhatsAppText(context, msg, phone)
    }

    fun buildCustomerReportText(
        visit: VisitEntity,
        customer: CustomerEntity?,
        entries: List<PurchaseEntryEntity>
    ): String {
        val totalAmount = entries.sumOf { it.totalAmount }
        val totalGst = entries.sumOf { it.gstAmount }
        val grandTotal = totalAmount + totalGst
        val totalCases = entries.sumOf { it.caseCount }
        val totalLoose = entries.sumOf { it.loosePieces }

        return buildString {
            appendLine("📋 *HIMAT TEXTILE — YOUR BUSINESS GUIDE ACROSS INDIA*")
            appendLine("Customer Day Report & Multi-Supplier Sourcing Summary")
            appendLine("─────────────────────────")
            appendLine("👤 *Customer:* ${customer?.name ?: visit.customerName}")
            appendLine("📍 *Market:* ${customer?.city ?: "—"}")
            appendLine("📅 *Date:* ${visit.date} | *Visit Code:* ${visit.visitCode}")
            appendLine("🤵 *Salesman:* ${visit.employeeName}")
            appendLine("─────────────────────────")
            appendLine("📦 *ITEMS PURCHASED:*")

            entries.groupBy { it.supplierName }.forEach { (supplier, items) ->
                appendLine("\n🏢 *${supplier}*")
                items.forEach { item ->
                    appendLine(" • *${item.itemCode}* | ${item.pieces} Pcs @ ₹${item.rate.toInt()} = ₹${item.totalAmount.toInt()}")
                    val pack = if (item.loosePieces > 0) "${item.caseCount}c + ${item.loosePieces}L" else "${item.caseCount}c"
                    appendLine("   Packing: $pack")
                    if (!item.mixedPackNote.isNullOrBlank()) {
                        appendLine("   ↳ _${item.mixedPackNote}_")
                    }
                }
            }

            appendLine("\n─────────────────────────")
            appendLine("📊 *TOTALS:*")
            appendLine("Total Quantity: ${entries.sumOf { it.pieces }} Pcs ($totalCases Cases, $totalLoose Loose)")
            appendLine("Subtotal: ₹${String.format("%,.2f", totalAmount)}")
            appendLine("Garment GST (5%): ₹${String.format("%,.2f", totalGst)}")
            appendLine("💰 *GRAND TOTAL: ₹${String.format("%,.2f", grandTotal)}*")
            appendLine("─────────────────────────")
            appendLine("_Himat Textile — Your Business Guide Across India_")
        }
    }

    fun buildSupplierCopyText(
        visit: VisitEntity,
        supplier: SupplierEntity,
        customer: CustomerEntity?,
        entries: List<PurchaseEntryEntity>
    ): String {
        val totalAmount = entries.sumOf { it.totalAmount }
        val totalGst = entries.sumOf { it.gstAmount }
        val grandTotal = totalAmount + totalGst

        return buildString {
            appendLine("🏷️ *HIMAT TEXTILE — YOUR BUSINESS GUIDE ACROSS INDIA*")
            appendLine("Supplier Purchase Order Copy")
            appendLine("─────────────────────────")
            appendLine("🏭 *Supplier:* ${supplier.name} (${supplier.type})")
            appendLine("📍 *Market Area:* ${supplier.marketArea}")
            appendLine("👤 *Customer:* ${customer?.name ?: visit.customerName}")
            appendLine("📅 *Date:* ${visit.date} | *Agent:* ${visit.employeeName}")
            appendLine("─────────────────────────")
            appendLine("📋 *PURCHASE DETAILS:*")

            entries.forEach { item ->
                appendLine(" • *Order ${item.orderNo}*: ${item.itemCode}")
                appendLine("   Qty: ${item.pieces} Pcs @ ₹${item.rate.toInt()} = ₹${item.totalAmount.toInt()}")
                val packing = if (item.loosePieces > 0) "${item.caseCount} Cases + ${item.loosePieces} Loose" else "${item.caseCount} Cases"
                appendLine("   Packing: $packing (Case size: ${item.caseSize})")
                if (!item.mixedPackNote.isNullOrBlank()) {
                    appendLine("   ⚠️ *Packing Note:* _${item.mixedPackNote}_")
                }
            }

            appendLine("\n─────────────────────────")
            appendLine("Total Pcs: ${entries.sumOf { it.pieces }} Pcs")
            appendLine("Taxable Amount: ₹${String.format("%,.2f", totalAmount)}")
            appendLine("GST (5%): ₹${String.format("%,.2f", totalGst)}")
            appendLine("💰 *NET TOTAL: ₹${String.format("%,.2f", grandTotal)}*")
            appendLine("─────────────────────────")
            appendLine("_Himat Textile — Your Business Guide Across India_")
        }
    }
}
