package com.example.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.local.entity.CustomerEntity
import com.example.data.local.entity.EmployeeEntity
import com.example.data.local.entity.PurchaseEntryEntity
import com.example.data.local.entity.SupplierEntity
import com.example.data.local.entity.VisitEntity
import java.io.File
import java.util.Locale

object ShareUtil {

    /**
     * The web admin, which is where anything this app deliberately does not carry lives.
     *
     * The bin is the main one: records deleted for good are reviewed and emptied there and nowhere
     * else, so the phone only needs to know how to get to it.
     */
    const val WEB_ADMIN_URL = "https://himatsms.web.app"
    const val WEB_BIN_URL = "$WEB_ADMIN_URL/#/app/bin"

    /** Opens a link in the browser. Says so plainly if the phone has nothing that can. */
    fun openUrl(context: Context, url: String) {
        try {
            context.startActivity(
                Intent(Intent.ACTION_VIEW, Uri.parse(url)).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
            )
        } catch (_: Exception) {
            Toast.makeText(context, "No app on this phone can open that link", Toast.LENGTH_LONG).show()
        }
    }

    fun sharePdfFile(context: Context, file: File, title: String, targetPackage: String? = null) {
        try {
            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, title)
                putExtra(Intent.EXTRA_TEXT, "$title\nGenerated by Himat Textile Sourcing Agency")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                if (targetPackage != null) {
                    setPackage(targetPackage)
                }
            }

            if (targetPackage != null) {
                try {
                    context.startActivity(shareIntent)
                    return
                } catch (e: Exception) {
                    // WhatsApp not installed or package mismatch, fallback to chooser
                }
            }

            val chooser = Intent.createChooser(shareIntent, "Share Document via")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            Toast.makeText(context, "Could not share PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun shareWhatsAppText(context: Context, text: String, phone: String? = null) {
        try {
            if (!phone.isNullOrBlank()) {
                val clean = phone.replace("+", "").replace("-", "").replace(" ", "").trim()
                val targetPhone = if (clean.length == 10) "91$clean" else clean
                val uri = Uri.parse("https://api.whatsapp.com/send?phone=$targetPhone&text=${Uri.encode(text)}")
                val intent = Intent(Intent.ACTION_VIEW, uri).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(intent)
                return
            }

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
                setPackage("com.whatsapp")
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(intent)
        } catch (e: Exception) {
            // Fallback to general share
            val fallback = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, text)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(Intent.createChooser(fallback, "Share via").apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            })
        }
    }

    /** Public customer registration page. With [subAgentId] the customer is linked to that Sub Agent. */
    fun customerRegistrationUrl(subAgentId: Long? = null): String {
        val base = "https://himatsms.web.app/#/register-customer"
        return if (subAgentId != null && subAgentId > 0L) "$base?agent=$subAgentId" else base
    }

    fun shareCustomerRegistrationLink(context: Context, phone: String? = null, subAgentId: Long? = null) {
        val regUrl = customerRegistrationUrl(subAgentId)
        val msg = """
            HIMAT TEXTILE AHMEDABAD
            Your Garment Guide Across India

            Hello,

            Thank you for choosing Himat Textile Ahmedabad.

            To open your New Customer Trade Account, please complete your business and contact details using the link below:

            🔗 Customer Registration:
            $regUrl

            Important: After submitting the registration form, you will receive an SMS OTP on your registered mobile number for verification.

            Once your registration is completed, our team will review your details and proceed with the account-opening process.

            Thank you for connecting with us.
            Himat Textile Ahmedabad
            Your Garment Guide Across India
        """.trimIndent()
        shareWhatsAppText(context, msg, phone)
    }

    fun shareSupplierRegistrationLink(context: Context, phone: String? = null) {
        val regUrl = "https://himatsms.web.app/#/register-supplier"
        val msg = """
            HIMAT TEXTILE AHMEDABAD
            Your Garment Guide Across India

            Hello,

            Thank you for connecting with Himat Textile Ahmedabad.

            To register as a Supplier with us, please complete your firm and business details using the link below:

            🔗 Supplier Registration:
            $regUrl

            Once your registration is submitted, our team will review your details and proceed with onboarding.

            Thank you!
            Himat Textile Ahmedabad
            Your Garment Guide Across India
        """.trimIndent()
        shareWhatsAppText(context, msg, phone)
    }

    fun buildCustomerReportText(
        visit: VisitEntity,
        customer: CustomerEntity?,
        entries: List<PurchaseEntryEntity>
    ): String {
        val totalPieces = entries.sumOf { it.pieces }
        val totalAmount = entries.sumOf { it.totalAmount }
        val totalGst = entries.sumOf { it.gstAmount }
        val grandTotal = totalAmount + totalGst
        val totalCases = entries.sumOf { it.caseCount }
        val totalLoose = entries.sumOf { it.loosePieces }
        val totalPaid = entries.sumOf { it.paidAmount }
        val totalDue = kotlin.math.max(0.0, grandTotal - totalPaid)

        val custBrand = (if (!customer?.firmName.isNullOrBlank()) customer?.firmName else customer?.name ?: visit.customerName).orEmpty().uppercase()
        val primaryTransporter = entries.find { it.transporter.isNotBlank() }?.transporter
            ?: (if (!customer?.preferredTransporterName.isNullOrBlank()) customer?.preferredTransporterName else customer?.transportPreference)
            ?: "Direct / Self Pickup"
        val bookingStation = if (!customer?.city.isNullOrBlank()) customer?.city!! else "Ahmedabad"
        // Everybody who worked this trip: per-order salesmen first, then all trip members
        val tripAgents = salesmenForReport(visit, entries).joinToString(", ").ifBlank { visit.employeeName }

        return buildString {
            appendLine("📋 *HIMAT TEXTILE — YOUR GARMENT GUIDE ACROSS INDIA*")
            appendLine("*CUSTOMER PURCHASE REPORT*")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("🏢 *Buyer / Firm:* *$custBrand*")
            val contact = customer?.name.orEmpty()
            if (contact.isNotBlank() && !contact.equals(custBrand, ignoreCase = true)) {
                appendLine("👤 *Proprietor / Contact:* $contact")
            }
            appendLine("📍 *City / Station:* $bookingStation")
            appendLine("🚛 *Transporter:* *$primaryTransporter*")
            appendLine("📋 *Trip Code:* ${visit.visitCode} | 📅 *Date:* ${visit.date}")
            appendLine("👔 *Trip Agents:* $tripAgents")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("📦 *PURCHASE ORDERS SUMMARY:*")

            entries.forEachIndexed { idx, item ->
                val sm = if (item.salesmanName.isNotBlank()) item.salesmanName else visit.employeeName
                val date = if (item.orderDate.isNotBlank()) item.orderDate else visit.date
                val pack = if (item.loosePieces > 0) "${item.caseCount}c + ${item.loosePieces}L" else "${item.caseCount} cs"
                val status = item.deliveryStatus.ifBlank { "Pending" }
                appendLine("${idx + 1}. *${item.itemCode}* — ${item.supplierName}")
                appendLine("   Qty: ${item.pieces} Pcs ($pack) @ ₹${item.rate.toInt()} = *₹${String.format(Locale.US, "%,.2f", item.totalAmount)}*")
                appendLine("   Status: *$status* | Salesman: $sm | Date: $date")
                if (!item.mixedPackNote.isNullOrBlank()) {
                    appendLine("   ↳ _Note: ${item.mixedPackNote}_")
                }
            }

            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("📊 *TOTALS & SETTLEMENT:*")
            appendLine("Total Quantity: $totalPieces Pcs ($totalCases Cases ${if (totalLoose > 0) "+ $totalLoose Loose" else ""})")
            appendLine("Subtotal: ₹${String.format(Locale.US, "%,.2f", totalAmount)}")
            appendLine("Garment GST (5%): ₹${String.format(Locale.US, "%,.2f", totalGst)}")
            appendLine("💰 *GRAND TOTAL: ₹${String.format(Locale.US, "%,.2f", grandTotal)}*")
            appendLine("✅ Paid: ₹${String.format(Locale.US, "%,.2f", totalPaid)}")
            appendLine("⚠️ Balance Due: ₹${String.format(Locale.US, "%,.2f", totalDue)}")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("🏦 *BANK PAYMENT DETAILS:*")
            appendLine("Bank: ICICI Bank (Ashram Road, Ahmedabad)")
            appendLine("A/C Name: HIMAT TEXTILE")
            appendLine("A/C No: 136805501447 | Type: Current")
            appendLine("IFSC: ICIC0000189")
            appendLine("UPI ID: eazypay.0000053310@icici")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("🌐 *Website:* https://himattextile.com")
            appendLine("_Himat Textile — Your Garment Guide Across India_")
        }
    }

    fun buildSupplierCopyText(
        visit: VisitEntity,
        supplier: SupplierEntity,
        customer: CustomerEntity?,
        entries: List<PurchaseEntryEntity>
    ): String {
        val totalPieces = entries.sumOf { it.pieces }
        val totalCases = entries.sumOf { it.caseCount }
        val totalAmount = entries.sumOf { it.totalAmount }
        val totalGst = entries.sumOf { it.gstAmount }
        val grandTotal = totalAmount + totalGst
        val suppBrand = if (supplier.brand.isNotBlank()) supplier.brand.uppercase() else supplier.name.uppercase()
        val custId = if (!customer?.customerId.isNullOrBlank()) customer?.customerId!! else if (customer != null && customer.id > 0) "CUST-${customer.id}" else if (visit.customerId > 0) "CUST-${visit.customerId}" else "CUST-TRADE"
        val buyerCity = customer?.city ?: "Ahmedabad"

        return buildString {
            appendLine("*HIMAT TEXTILE — YOUR GARMENT GUIDE ACROSS INDIA*")
            appendLine("📝 *ORDER FORM (DRAFT BILL)*")
            appendLine("⚠️ _All amounts are approximate • One Bill One LR_")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("🏭 *Supplier Brand:* *$suppBrand*")
            if (supplier.name.isNotBlank() && !supplier.name.equals(suppBrand, ignoreCase = true)) {
                appendLine("🏢 *Firm:* ${supplier.name}")
            }
            appendLine("🆔 *Customer ID:* *$custId* ($buyerCity)")
            appendLine("📅 *Date:* ${visit.date} | *Trip:* ${visit.visitCode}")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("📋 *ORDER ITEMS:*")

            entries.forEachIndexed { idx, item ->
                val pack = if (item.loosePieces > 0) "${item.caseCount}c + ${item.loosePieces}L" else "${item.caseCount} cases"
                appendLine("${idx + 1}. *${item.itemCode}* — ${item.pieces} pcs ($pack)")
                appendLine("   Approx Rate: ₹${item.rate.toInt()} | Approx Amt: ₹${String.format(Locale.US, "%,.2f", item.totalAmount)}")
                if (!item.mixedPackNote.isNullOrBlank()) {
                    appendLine("   ↳ _Note: ${item.mixedPackNote}_")
                }
            }

            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("📦 *Total Qty:* $totalPieces Pcs ($totalCases Cases)")
            appendLine("💰 *Approx Net Total:* ₹${String.format(Locale.US, "%,.2f", grandTotal)}")
            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine("📌 *Note:* One Bill One LR. All amounts are approximate estimates.")
            appendLine("🌐 *Website:* https://himattextile.com")
            appendLine("_Himat Textile — Your Garment Guide Across India_")
        }
    }
}
